name: 'CodeYet'
description: 'Upload metrics to CodeYet'
author: 'https://codeyet.dev'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'Repository token'
    required: true
  api:
    description: 'API Endpoint'

# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
